template: testify
formatter: goimports
force-file-write: true
packages:
  e-wallet/internal/ports:
    config:
      all: true
      dir: "{{.InterfaceDir}}"
      filename: "mocks_test.go"
      pkgname: "{{.PackageName}}_test"
      structname: "Mock{{.InterfaceName}}"
