// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"e-wallet/internal/domain/account"
	"e-wallet/internal/domain/profile"
	"e-wallet/internal/domain/user"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

type MockAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepository) EXPECT() *MockAccountRepository_Expecter {
	return &MockAccountRepository_Expecter{mock: &_m.Mock}
}

// CountPaymentAccountsByUserID provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) CountPaymentAccountsByUserID(ctx context.Context, userID string) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountPaymentAccountsByUserID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_CountPaymentAccountsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountPaymentAccountsByUserID'
type MockAccountRepository_CountPaymentAccountsByUserID_Call struct {
	*mock.Call
}

// CountPaymentAccountsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAccountRepository_Expecter) CountPaymentAccountsByUserID(ctx interface{}, userID interface{}) *MockAccountRepository_CountPaymentAccountsByUserID_Call {
	return &MockAccountRepository_CountPaymentAccountsByUserID_Call{Call: _e.mock.On("CountPaymentAccountsByUserID", ctx, userID)}
}

func (_c *MockAccountRepository_CountPaymentAccountsByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockAccountRepository_CountPaymentAccountsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_CountPaymentAccountsByUserID_Call) Return(n int64, err error) *MockAccountRepository_CountPaymentAccountsByUserID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAccountRepository_CountPaymentAccountsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (int64, error)) *MockAccountRepository_CountPaymentAccountsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// CountSavingsAccountsByUserID provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) CountSavingsAccountsByUserID(ctx context.Context, userID string) (int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountSavingsAccountsByUserID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_CountSavingsAccountsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSavingsAccountsByUserID'
type MockAccountRepository_CountSavingsAccountsByUserID_Call struct {
	*mock.Call
}

// CountSavingsAccountsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAccountRepository_Expecter) CountSavingsAccountsByUserID(ctx interface{}, userID interface{}) *MockAccountRepository_CountSavingsAccountsByUserID_Call {
	return &MockAccountRepository_CountSavingsAccountsByUserID_Call{Call: _e.mock.On("CountSavingsAccountsByUserID", ctx, userID)}
}

func (_c *MockAccountRepository_CountSavingsAccountsByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockAccountRepository_CountSavingsAccountsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_CountSavingsAccountsByUserID_Call) Return(n int64, err error) *MockAccountRepository_CountSavingsAccountsByUserID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAccountRepository_CountSavingsAccountsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (int64, error)) *MockAccountRepository_CountSavingsAccountsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFixedSavingsAccount provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) CreateFixedSavingsAccount(ctx context.Context, userID string, req *account.CreateFixedSavingsAccountRequest) (*account.Account, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateFixedSavingsAccount")
	}

	var r0 *account.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *account.CreateFixedSavingsAccountRequest) (*account.Account, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *account.CreateFixedSavingsAccountRequest) *account.Account); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *account.CreateFixedSavingsAccountRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_CreateFixedSavingsAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFixedSavingsAccount'
type MockAccountRepository_CreateFixedSavingsAccount_Call struct {
	*mock.Call
}

// CreateFixedSavingsAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req *account.CreateFixedSavingsAccountRequest
func (_e *MockAccountRepository_Expecter) CreateFixedSavingsAccount(ctx interface{}, userID interface{}, req interface{}) *MockAccountRepository_CreateFixedSavingsAccount_Call {
	return &MockAccountRepository_CreateFixedSavingsAccount_Call{Call: _e.mock.On("CreateFixedSavingsAccount", ctx, userID, req)}
}

func (_c *MockAccountRepository_CreateFixedSavingsAccount_Call) Run(run func(ctx context.Context, userID string, req *account.CreateFixedSavingsAccountRequest)) *MockAccountRepository_CreateFixedSavingsAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *account.CreateFixedSavingsAccountRequest
		if args[2] != nil {
			arg2 = args[2].(*account.CreateFixedSavingsAccountRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountRepository_CreateFixedSavingsAccount_Call) Return(account1 *account.Account, err error) *MockAccountRepository_CreateFixedSavingsAccount_Call {
	_c.Call.Return(account1, err)
	return _c
}

func (_c *MockAccountRepository_CreateFixedSavingsAccount_Call) RunAndReturn(run func(ctx context.Context, userID string, req *account.CreateFixedSavingsAccountRequest) (*account.Account, error)) *MockAccountRepository_CreateFixedSavingsAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFlexibleSavingsAccount provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) CreateFlexibleSavingsAccount(ctx context.Context, userID string) (*account.Account, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateFlexibleSavingsAccount")
	}

	var r0 *account.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*account.Account, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *account.Account); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_CreateFlexibleSavingsAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFlexibleSavingsAccount'
type MockAccountRepository_CreateFlexibleSavingsAccount_Call struct {
	*mock.Call
}

// CreateFlexibleSavingsAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAccountRepository_Expecter) CreateFlexibleSavingsAccount(ctx interface{}, userID interface{}) *MockAccountRepository_CreateFlexibleSavingsAccount_Call {
	return &MockAccountRepository_CreateFlexibleSavingsAccount_Call{Call: _e.mock.On("CreateFlexibleSavingsAccount", ctx, userID)}
}

func (_c *MockAccountRepository_CreateFlexibleSavingsAccount_Call) Run(run func(ctx context.Context, userID string)) *MockAccountRepository_CreateFlexibleSavingsAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_CreateFlexibleSavingsAccount_Call) Return(account1 *account.Account, err error) *MockAccountRepository_CreateFlexibleSavingsAccount_Call {
	_c.Call.Return(account1, err)
	return _c
}

func (_c *MockAccountRepository_CreateFlexibleSavingsAccount_Call) RunAndReturn(run func(ctx context.Context, userID string) (*account.Account, error)) *MockAccountRepository_CreateFlexibleSavingsAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePaymentAccount provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) CreatePaymentAccount(ctx context.Context, userID string) (*account.Account, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentAccount")
	}

	var r0 *account.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*account.Account, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *account.Account); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_CreatePaymentAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePaymentAccount'
type MockAccountRepository_CreatePaymentAccount_Call struct {
	*mock.Call
}

// CreatePaymentAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAccountRepository_Expecter) CreatePaymentAccount(ctx interface{}, userID interface{}) *MockAccountRepository_CreatePaymentAccount_Call {
	return &MockAccountRepository_CreatePaymentAccount_Call{Call: _e.mock.On("CreatePaymentAccount", ctx, userID)}
}

func (_c *MockAccountRepository_CreatePaymentAccount_Call) Run(run func(ctx context.Context, userID string)) *MockAccountRepository_CreatePaymentAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_CreatePaymentAccount_Call) Return(account1 *account.Account, err error) *MockAccountRepository_CreatePaymentAccount_Call {
	_c.Call.Return(account1, err)
	return _c
}

func (_c *MockAccountRepository_CreatePaymentAccount_Call) RunAndReturn(run func(ctx context.Context, userID string) (*account.Account, error)) *MockAccountRepository_CreatePaymentAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountByID provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) GetAccountByID(ctx context.Context, accountID string) (*account.Account, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountByID")
	}

	var r0 *account.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*account.Account, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *account.Account); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_GetAccountByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountByID'
type MockAccountRepository_GetAccountByID_Call struct {
	*mock.Call
}

// GetAccountByID is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockAccountRepository_Expecter) GetAccountByID(ctx interface{}, accountID interface{}) *MockAccountRepository_GetAccountByID_Call {
	return &MockAccountRepository_GetAccountByID_Call{Call: _e.mock.On("GetAccountByID", ctx, accountID)}
}

func (_c *MockAccountRepository_GetAccountByID_Call) Run(run func(ctx context.Context, accountID string)) *MockAccountRepository_GetAccountByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_GetAccountByID_Call) Return(account1 *account.Account, err error) *MockAccountRepository_GetAccountByID_Call {
	_c.Call.Return(account1, err)
	return _c
}

func (_c *MockAccountRepository_GetAccountByID_Call) RunAndReturn(run func(ctx context.Context, accountID string) (*account.Account, error)) *MockAccountRepository_GetAccountByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountsByUserID provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) GetAccountsByUserID(ctx context.Context, userID string) ([]*account.Account, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountsByUserID")
	}

	var r0 []*account.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*account.Account, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*account.Account); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*account.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_GetAccountsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountsByUserID'
type MockAccountRepository_GetAccountsByUserID_Call struct {
	*mock.Call
}

// GetAccountsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAccountRepository_Expecter) GetAccountsByUserID(ctx interface{}, userID interface{}) *MockAccountRepository_GetAccountsByUserID_Call {
	return &MockAccountRepository_GetAccountsByUserID_Call{Call: _e.mock.On("GetAccountsByUserID", ctx, userID)}
}

func (_c *MockAccountRepository_GetAccountsByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockAccountRepository_GetAccountsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_GetAccountsByUserID_Call) Return(accounts []*account.Account, err error) *MockAccountRepository_GetAccountsByUserID_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockAccountRepository_GetAccountsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]*account.Account, error)) *MockAccountRepository_GetAccountsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccountBalance provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) UpdateAccountBalance(ctx context.Context, accountID string, newBalance float64) error {
	ret := _mock.Called(ctx, accountID, newBalance)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccountBalance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, float64) error); ok {
		r0 = returnFunc(ctx, accountID, newBalance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountRepository_UpdateAccountBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccountBalance'
type MockAccountRepository_UpdateAccountBalance_Call struct {
	*mock.Call
}

// UpdateAccountBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - newBalance float64
func (_e *MockAccountRepository_Expecter) UpdateAccountBalance(ctx interface{}, accountID interface{}, newBalance interface{}) *MockAccountRepository_UpdateAccountBalance_Call {
	return &MockAccountRepository_UpdateAccountBalance_Call{Call: _e.mock.On("UpdateAccountBalance", ctx, accountID, newBalance)}
}

func (_c *MockAccountRepository_UpdateAccountBalance_Call) Run(run func(ctx context.Context, accountID string, newBalance float64)) *MockAccountRepository_UpdateAccountBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountRepository_UpdateAccountBalance_Call) Return(err error) *MockAccountRepository_UpdateAccountBalance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountRepository_UpdateAccountBalance_Call) RunAndReturn(run func(ctx context.Context, accountID string, newBalance float64) error) *MockAccountRepository_UpdateAccountBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSavingsAccountDetailRepository creates a new instance of MockSavingsAccountDetailRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSavingsAccountDetailRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSavingsAccountDetailRepository {
	mock := &MockSavingsAccountDetailRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSavingsAccountDetailRepository is an autogenerated mock type for the SavingsAccountDetailRepository type
type MockSavingsAccountDetailRepository struct {
	mock.Mock
}

type MockSavingsAccountDetailRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSavingsAccountDetailRepository) EXPECT() *MockSavingsAccountDetailRepository_Expecter {
	return &MockSavingsAccountDetailRepository_Expecter{mock: &_m.Mock}
}

// CreateSavingsAccountDetail provides a mock function for the type MockSavingsAccountDetailRepository
func (_mock *MockSavingsAccountDetailRepository) CreateSavingsAccountDetail(ctx context.Context, detail *account.SavingsAccountDetail) error {
	ret := _mock.Called(ctx, detail)

	if len(ret) == 0 {
		panic("no return value specified for CreateSavingsAccountDetail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *account.SavingsAccountDetail) error); ok {
		r0 = returnFunc(ctx, detail)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSavingsAccountDetailRepository_CreateSavingsAccountDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSavingsAccountDetail'
type MockSavingsAccountDetailRepository_CreateSavingsAccountDetail_Call struct {
	*mock.Call
}

// CreateSavingsAccountDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - detail *account.SavingsAccountDetail
func (_e *MockSavingsAccountDetailRepository_Expecter) CreateSavingsAccountDetail(ctx interface{}, detail interface{}) *MockSavingsAccountDetailRepository_CreateSavingsAccountDetail_Call {
	return &MockSavingsAccountDetailRepository_CreateSavingsAccountDetail_Call{Call: _e.mock.On("CreateSavingsAccountDetail", ctx, detail)}
}

func (_c *MockSavingsAccountDetailRepository_CreateSavingsAccountDetail_Call) Run(run func(ctx context.Context, detail *account.SavingsAccountDetail)) *MockSavingsAccountDetailRepository_CreateSavingsAccountDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *account.SavingsAccountDetail
		if args[1] != nil {
			arg1 = args[1].(*account.SavingsAccountDetail)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSavingsAccountDetailRepository_CreateSavingsAccountDetail_Call) Return(err error) *MockSavingsAccountDetailRepository_CreateSavingsAccountDetail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSavingsAccountDetailRepository_CreateSavingsAccountDetail_Call) RunAndReturn(run func(ctx context.Context, detail *account.SavingsAccountDetail) error) *MockSavingsAccountDetailRepository_CreateSavingsAccountDetail_Call {
	_c.Call.Return(run)
	return _c
}

// GetSavingsAccountDetailByAccountID provides a mock function for the type MockSavingsAccountDetailRepository
func (_mock *MockSavingsAccountDetailRepository) GetSavingsAccountDetailByAccountID(ctx context.Context, accountID string) (*account.SavingsAccountDetail, error) {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetSavingsAccountDetailByAccountID")
	}

	var r0 *account.SavingsAccountDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*account.SavingsAccountDetail, error)); ok {
		return returnFunc(ctx, accountID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *account.SavingsAccountDetail); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.SavingsAccountDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSavingsAccountDetailRepository_GetSavingsAccountDetailByAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSavingsAccountDetailByAccountID'
type MockSavingsAccountDetailRepository_GetSavingsAccountDetailByAccountID_Call struct {
	*mock.Call
}

// GetSavingsAccountDetailByAccountID is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockSavingsAccountDetailRepository_Expecter) GetSavingsAccountDetailByAccountID(ctx interface{}, accountID interface{}) *MockSavingsAccountDetailRepository_GetSavingsAccountDetailByAccountID_Call {
	return &MockSavingsAccountDetailRepository_GetSavingsAccountDetailByAccountID_Call{Call: _e.mock.On("GetSavingsAccountDetailByAccountID", ctx, accountID)}
}

func (_c *MockSavingsAccountDetailRepository_GetSavingsAccountDetailByAccountID_Call) Run(run func(ctx context.Context, accountID string)) *MockSavingsAccountDetailRepository_GetSavingsAccountDetailByAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSavingsAccountDetailRepository_GetSavingsAccountDetailByAccountID_Call) Return(savingsAccountDetail *account.SavingsAccountDetail, err error) *MockSavingsAccountDetailRepository_GetSavingsAccountDetailByAccountID_Call {
	_c.Call.Return(savingsAccountDetail, err)
	return _c
}

func (_c *MockSavingsAccountDetailRepository_GetSavingsAccountDetailByAccountID_Call) RunAndReturn(run func(ctx context.Context, accountID string) (*account.SavingsAccountDetail, error)) *MockSavingsAccountDetailRepository_GetSavingsAccountDetailByAccountID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastInterestCalcDate provides a mock function for the type MockSavingsAccountDetailRepository
func (_mock *MockSavingsAccountDetailRepository) UpdateLastInterestCalcDate(ctx context.Context, accountID string, date *time.Time) error {
	ret := _mock.Called(ctx, accountID, date)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastInterestCalcDate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *time.Time) error); ok {
		r0 = returnFunc(ctx, accountID, date)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSavingsAccountDetailRepository_UpdateLastInterestCalcDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastInterestCalcDate'
type MockSavingsAccountDetailRepository_UpdateLastInterestCalcDate_Call struct {
	*mock.Call
}

// UpdateLastInterestCalcDate is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - date *time.Time
func (_e *MockSavingsAccountDetailRepository_Expecter) UpdateLastInterestCalcDate(ctx interface{}, accountID interface{}, date interface{}) *MockSavingsAccountDetailRepository_UpdateLastInterestCalcDate_Call {
	return &MockSavingsAccountDetailRepository_UpdateLastInterestCalcDate_Call{Call: _e.mock.On("UpdateLastInterestCalcDate", ctx, accountID, date)}
}

func (_c *MockSavingsAccountDetailRepository_UpdateLastInterestCalcDate_Call) Run(run func(ctx context.Context, accountID string, date *time.Time)) *MockSavingsAccountDetailRepository_UpdateLastInterestCalcDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSavingsAccountDetailRepository_UpdateLastInterestCalcDate_Call) Return(err error) *MockSavingsAccountDetailRepository_UpdateLastInterestCalcDate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSavingsAccountDetailRepository_UpdateLastInterestCalcDate_Call) RunAndReturn(run func(ctx context.Context, accountID string, date *time.Time) error) *MockSavingsAccountDetailRepository_UpdateLastInterestCalcDate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountService creates a new instance of MockAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountService {
	mock := &MockAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountService is an autogenerated mock type for the AccountService type
type MockAccountService struct {
	mock.Mock
}

type MockAccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountService) EXPECT() *MockAccountService_Expecter {
	return &MockAccountService_Expecter{mock: &_m.Mock}
}

// CreateFixedSavingsAccount provides a mock function for the type MockAccountService
func (_mock *MockAccountService) CreateFixedSavingsAccount(ctx context.Context, userID string, req *account.CreateFixedSavingsAccountRequest) (*account.Account, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateFixedSavingsAccount")
	}

	var r0 *account.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *account.CreateFixedSavingsAccountRequest) (*account.Account, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *account.CreateFixedSavingsAccountRequest) *account.Account); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *account.CreateFixedSavingsAccountRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountService_CreateFixedSavingsAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFixedSavingsAccount'
type MockAccountService_CreateFixedSavingsAccount_Call struct {
	*mock.Call
}

// CreateFixedSavingsAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req *account.CreateFixedSavingsAccountRequest
func (_e *MockAccountService_Expecter) CreateFixedSavingsAccount(ctx interface{}, userID interface{}, req interface{}) *MockAccountService_CreateFixedSavingsAccount_Call {
	return &MockAccountService_CreateFixedSavingsAccount_Call{Call: _e.mock.On("CreateFixedSavingsAccount", ctx, userID, req)}
}

func (_c *MockAccountService_CreateFixedSavingsAccount_Call) Run(run func(ctx context.Context, userID string, req *account.CreateFixedSavingsAccountRequest)) *MockAccountService_CreateFixedSavingsAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *account.CreateFixedSavingsAccountRequest
		if args[2] != nil {
			arg2 = args[2].(*account.CreateFixedSavingsAccountRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountService_CreateFixedSavingsAccount_Call) Return(account1 *account.Account, err error) *MockAccountService_CreateFixedSavingsAccount_Call {
	_c.Call.Return(account1, err)
	return _c
}

func (_c *MockAccountService_CreateFixedSavingsAccount_Call) RunAndReturn(run func(ctx context.Context, userID string, req *account.CreateFixedSavingsAccountRequest) (*account.Account, error)) *MockAccountService_CreateFixedSavingsAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreateFlexibleSavingsAccount provides a mock function for the type MockAccountService
func (_mock *MockAccountService) CreateFlexibleSavingsAccount(ctx context.Context, userID string) (*account.Account, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateFlexibleSavingsAccount")
	}

	var r0 *account.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*account.Account, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *account.Account); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountService_CreateFlexibleSavingsAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFlexibleSavingsAccount'
type MockAccountService_CreateFlexibleSavingsAccount_Call struct {
	*mock.Call
}

// CreateFlexibleSavingsAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAccountService_Expecter) CreateFlexibleSavingsAccount(ctx interface{}, userID interface{}) *MockAccountService_CreateFlexibleSavingsAccount_Call {
	return &MockAccountService_CreateFlexibleSavingsAccount_Call{Call: _e.mock.On("CreateFlexibleSavingsAccount", ctx, userID)}
}

func (_c *MockAccountService_CreateFlexibleSavingsAccount_Call) Run(run func(ctx context.Context, userID string)) *MockAccountService_CreateFlexibleSavingsAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_CreateFlexibleSavingsAccount_Call) Return(account1 *account.Account, err error) *MockAccountService_CreateFlexibleSavingsAccount_Call {
	_c.Call.Return(account1, err)
	return _c
}

func (_c *MockAccountService_CreateFlexibleSavingsAccount_Call) RunAndReturn(run func(ctx context.Context, userID string) (*account.Account, error)) *MockAccountService_CreateFlexibleSavingsAccount_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePaymentAccount provides a mock function for the type MockAccountService
func (_mock *MockAccountService) CreatePaymentAccount(ctx context.Context, userID string) (*account.Account, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePaymentAccount")
	}

	var r0 *account.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*account.Account, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *account.Account); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountService_CreatePaymentAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePaymentAccount'
type MockAccountService_CreatePaymentAccount_Call struct {
	*mock.Call
}

// CreatePaymentAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAccountService_Expecter) CreatePaymentAccount(ctx interface{}, userID interface{}) *MockAccountService_CreatePaymentAccount_Call {
	return &MockAccountService_CreatePaymentAccount_Call{Call: _e.mock.On("CreatePaymentAccount", ctx, userID)}
}

func (_c *MockAccountService_CreatePaymentAccount_Call) Run(run func(ctx context.Context, userID string)) *MockAccountService_CreatePaymentAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_CreatePaymentAccount_Call) Return(account1 *account.Account, err error) *MockAccountService_CreatePaymentAccount_Call {
	_c.Call.Return(account1, err)
	return _c
}

func (_c *MockAccountService_CreatePaymentAccount_Call) RunAndReturn(run func(ctx context.Context, userID string) (*account.Account, error)) *MockAccountService_CreatePaymentAccount_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccounts provides a mock function for the type MockAccountService
func (_mock *MockAccountService) ListAccounts(ctx context.Context, userID string) (*account.ListAccountsResponse, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListAccounts")
	}

	var r0 *account.ListAccountsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*account.ListAccountsResponse, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *account.ListAccountsResponse); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.ListAccountsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountService_ListAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccounts'
type MockAccountService_ListAccounts_Call struct {
	*mock.Call
}

// ListAccounts is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAccountService_Expecter) ListAccounts(ctx interface{}, userID interface{}) *MockAccountService_ListAccounts_Call {
	return &MockAccountService_ListAccounts_Call{Call: _e.mock.On("ListAccounts", ctx, userID)}
}

func (_c *MockAccountService_ListAccounts_Call) Run(run func(ctx context.Context, userID string)) *MockAccountService_ListAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_ListAccounts_Call) Return(listAccountsResponse *account.ListAccountsResponse, err error) *MockAccountService_ListAccounts_Call {
	_c.Call.Return(listAccountsResponse, err)
	return _c
}

func (_c *MockAccountService_ListAccounts_Call) RunAndReturn(run func(ctx context.Context, userID string) (*account.ListAccountsResponse, error)) *MockAccountService_ListAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordService creates a new instance of MockPasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordService {
	mock := &MockPasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPasswordService is an autogenerated mock type for the PasswordService type
type MockPasswordService struct {
	mock.Mock
}

type MockPasswordService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordService) EXPECT() *MockPasswordService_Expecter {
	return &MockPasswordService_Expecter{mock: &_m.Mock}
}

// CheckPassword provides a mock function for the type MockPasswordService
func (_mock *MockPasswordService) CheckPassword(hashedPassword string, password string) error {
	ret := _mock.Called(hashedPassword, password)

	if len(ret) == 0 {
		panic("no return value specified for CheckPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(hashedPassword, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPasswordService_CheckPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPassword'
type MockPasswordService_CheckPassword_Call struct {
	*mock.Call
}

// CheckPassword is a helper method to define mock.On call
//   - hashedPassword string
//   - password string
func (_e *MockPasswordService_Expecter) CheckPassword(hashedPassword interface{}, password interface{}) *MockPasswordService_CheckPassword_Call {
	return &MockPasswordService_CheckPassword_Call{Call: _e.mock.On("CheckPassword", hashedPassword, password)}
}

func (_c *MockPasswordService_CheckPassword_Call) Run(run func(hashedPassword string, password string)) *MockPasswordService_CheckPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPasswordService_CheckPassword_Call) Return(err error) *MockPasswordService_CheckPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPasswordService_CheckPassword_Call) RunAndReturn(run func(hashedPassword string, password string) error) *MockPasswordService_CheckPassword_Call {
	_c.Call.Return(run)
	return _c
}

// HashPassword provides a mock function for the type MockPasswordService
func (_mock *MockPasswordService) HashPassword(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPasswordService_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type MockPasswordService_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password string
func (_e *MockPasswordService_Expecter) HashPassword(password interface{}) *MockPasswordService_HashPassword_Call {
	return &MockPasswordService_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *MockPasswordService_HashPassword_Call) Run(run func(password string)) *MockPasswordService_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPasswordService_HashPassword_Call) Return(s string, err error) *MockPasswordService_HashPassword_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPasswordService_HashPassword_Call) RunAndReturn(run func(password string) (string, error)) *MockPasswordService_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProfileRepository creates a new instance of MockProfileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileRepository {
	mock := &MockProfileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileRepository is an autogenerated mock type for the ProfileRepository type
type MockProfileRepository struct {
	mock.Mock
}

type MockProfileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileRepository) EXPECT() *MockProfileRepository_Expecter {
	return &MockProfileRepository_Expecter{mock: &_m.Mock}
}

// CheckNationalIDExists provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) CheckNationalIDExists(ctx context.Context, nationalID string, excludeUserID string) (bool, error) {
	ret := _mock.Called(ctx, nationalID, excludeUserID)

	if len(ret) == 0 {
		panic("no return value specified for CheckNationalIDExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, nationalID, excludeUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, nationalID, excludeUserID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, nationalID, excludeUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_CheckNationalIDExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckNationalIDExists'
type MockProfileRepository_CheckNationalIDExists_Call struct {
	*mock.Call
}

// CheckNationalIDExists is a helper method to define mock.On call
//   - ctx context.Context
//   - nationalID string
//   - excludeUserID string
func (_e *MockProfileRepository_Expecter) CheckNationalIDExists(ctx interface{}, nationalID interface{}, excludeUserID interface{}) *MockProfileRepository_CheckNationalIDExists_Call {
	return &MockProfileRepository_CheckNationalIDExists_Call{Call: _e.mock.On("CheckNationalIDExists", ctx, nationalID, excludeUserID)}
}

func (_c *MockProfileRepository_CheckNationalIDExists_Call) Run(run func(ctx context.Context, nationalID string, excludeUserID string)) *MockProfileRepository_CheckNationalIDExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProfileRepository_CheckNationalIDExists_Call) Return(b bool, err error) *MockProfileRepository_CheckNationalIDExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockProfileRepository_CheckNationalIDExists_Call) RunAndReturn(run func(ctx context.Context, nationalID string, excludeUserID string) (bool, error)) *MockProfileRepository_CheckNationalIDExists_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) GetByUserID(ctx context.Context, userID string) (*profile.Profile, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *profile.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*profile.Profile, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *profile.Profile); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profile.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockProfileRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockProfileRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockProfileRepository_GetByUserID_Call {
	return &MockProfileRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockProfileRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockProfileRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_GetByUserID_Call) Return(profile1 *profile.Profile, err error) *MockProfileRepository_GetByUserID_Call {
	_c.Call.Return(profile1, err)
	return _c
}

func (_c *MockProfileRepository_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*profile.Profile, error)) *MockProfileRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockProfileRepository
func (_mock *MockProfileRepository) Upsert(ctx context.Context, profile1 *profile.Profile) (*profile.Profile, error) {
	ret := _mock.Called(ctx, profile1)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 *profile.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *profile.Profile) (*profile.Profile, error)); ok {
		return returnFunc(ctx, profile1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *profile.Profile) *profile.Profile); ok {
		r0 = returnFunc(ctx, profile1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profile.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *profile.Profile) error); ok {
		r1 = returnFunc(ctx, profile1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockProfileRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - profile1 *profile.Profile
func (_e *MockProfileRepository_Expecter) Upsert(ctx interface{}, profile1 interface{}) *MockProfileRepository_Upsert_Call {
	return &MockProfileRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, profile1)}
}

func (_c *MockProfileRepository_Upsert_Call) Run(run func(ctx context.Context, profile1 *profile.Profile)) *MockProfileRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *profile.Profile
		if args[1] != nil {
			arg1 = args[1].(*profile.Profile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileRepository_Upsert_Call) Return(profile11 *profile.Profile, err error) *MockProfileRepository_Upsert_Call {
	_c.Call.Return(profile11, err)
	return _c
}

func (_c *MockProfileRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, profile1 *profile.Profile) (*profile.Profile, error)) *MockProfileRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProfileService creates a new instance of MockProfileService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileService {
	mock := &MockProfileService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfileService is an autogenerated mock type for the ProfileService type
type MockProfileService struct {
	mock.Mock
}

type MockProfileService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileService) EXPECT() *MockProfileService_Expecter {
	return &MockProfileService_Expecter{mock: &_m.Mock}
}

// GetProfile provides a mock function for the type MockProfileService
func (_mock *MockProfileService) GetProfile(ctx context.Context, userID string) (*profile.Profile, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *profile.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*profile.Profile, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *profile.Profile); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profile.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockProfileService_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockProfileService_Expecter) GetProfile(ctx interface{}, userID interface{}) *MockProfileService_GetProfile_Call {
	return &MockProfileService_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, userID)}
}

func (_c *MockProfileService_GetProfile_Call) Run(run func(ctx context.Context, userID string)) *MockProfileService_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileService_GetProfile_Call) Return(profile1 *profile.Profile, err error) *MockProfileService_GetProfile_Call {
	_c.Call.Return(profile1, err)
	return _c
}

func (_c *MockProfileService_GetProfile_Call) RunAndReturn(run func(ctx context.Context, userID string) (*profile.Profile, error)) *MockProfileService_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type MockProfileService
func (_mock *MockProfileService) UpdateProfile(ctx context.Context, userID string, req *profile.UpdateProfileRequest) (*profile.Profile, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *profile.Profile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *profile.UpdateProfileRequest) (*profile.Profile, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *profile.UpdateProfileRequest) *profile.Profile); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profile.Profile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *profile.UpdateProfileRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockProfileService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - req *profile.UpdateProfileRequest
func (_e *MockProfileService_Expecter) UpdateProfile(ctx interface{}, userID interface{}, req interface{}) *MockProfileService_UpdateProfile_Call {
	return &MockProfileService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, req)}
}

func (_c *MockProfileService_UpdateProfile_Call) Run(run func(ctx context.Context, userID string, req *profile.UpdateProfileRequest)) *MockProfileService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *profile.UpdateProfileRequest
		if args[2] != nil {
			arg2 = args[2].(*profile.UpdateProfileRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProfileService_UpdateProfile_Call) Return(profile1 *profile.Profile, err error) *MockProfileService_UpdateProfile_Call {
	_c.Call.Return(profile1, err)
	return _c
}

func (_c *MockProfileService_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, userID string, req *profile.UpdateProfileRequest) (*profile.Profile, error)) *MockProfileService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Create(ctx context.Context, user1 *user.User) (*user.User, error) {
	ret := _mock.Called(ctx, user1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User) (*user.User, error)); ok {
		return returnFunc(ctx, user1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User) *user.User); ok {
		r0 = returnFunc(ctx, user1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *user.User) error); ok {
		r1 = returnFunc(ctx, user1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user1 *user.User
func (_e *MockUserRepository_Expecter) Create(ctx interface{}, user1 interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, user1)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, user1 *user.User)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(user11 *user.User, err error) *MockUserRepository_Create_Call {
	_c.Call.Return(user11, err)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, user1 *user.User) (*user.User, error)) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByEmail(ctx context.Context, email string) (*user.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockUserRepository_GetByEmail_Call {
	return &MockUserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) Return(user1 *user.User, err error) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*user.User, error)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByID(ctx context.Context, id string) (*user.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockUserRepository_GetByID_Call {
	return &MockUserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockUserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByID_Call) Return(user1 *user.User, err error) *MockUserRepository_GetByID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*user.User, error)) *MockUserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfileCompleted provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) UpdateProfileCompleted(ctx context.Context, id string, completed bool) error {
	ret := _mock.Called(ctx, id, completed)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfileCompleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, id, completed)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_UpdateProfileCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfileCompleted'
type MockUserRepository_UpdateProfileCompleted_Call struct {
	*mock.Call
}

// UpdateProfileCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - completed bool
func (_e *MockUserRepository_Expecter) UpdateProfileCompleted(ctx interface{}, id interface{}, completed interface{}) *MockUserRepository_UpdateProfileCompleted_Call {
	return &MockUserRepository_UpdateProfileCompleted_Call{Call: _e.mock.On("UpdateProfileCompleted", ctx, id, completed)}
}

func (_c *MockUserRepository_UpdateProfileCompleted_Call) Run(run func(ctx context.Context, id string, completed bool)) *MockUserRepository_UpdateProfileCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_UpdateProfileCompleted_Call) Return(err error) *MockUserRepository_UpdateProfileCompleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_UpdateProfileCompleted_Call) RunAndReturn(run func(ctx context.Context, id string, completed bool) error) *MockUserRepository_UpdateProfileCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserService
func (_mock *MockUserService) CreateUser(ctx context.Context, req *user.CreateUserRequest) (*user.User, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.CreateUserRequest) (*user.User, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.CreateUserRequest) *user.User); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *user.CreateUserRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - req *user.CreateUserRequest
func (_e *MockUserService_Expecter) CreateUser(ctx interface{}, req interface{}) *MockUserService_CreateUser_Call {
	return &MockUserService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, req)}
}

func (_c *MockUserService_CreateUser_Call) Run(run func(ctx context.Context, req *user.CreateUserRequest)) *MockUserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.CreateUserRequest
		if args[1] != nil {
			arg1 = args[1].(*user.CreateUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_CreateUser_Call) Return(user1 *user.User, err error) *MockUserService_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserService_CreateUser_Call) RunAndReturn(run func(ctx context.Context, req *user.CreateUserRequest) (*user.User, error)) *MockUserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// LoginUser provides a mock function for the type MockUserService
func (_mock *MockUserService) LoginUser(ctx context.Context, req *user.LoginUserRequest) (*user.User, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.LoginUserRequest) (*user.User, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.LoginUserRequest) *user.User); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *user.LoginUserRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_LoginUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginUser'
type MockUserService_LoginUser_Call struct {
	*mock.Call
}

// LoginUser is a helper method to define mock.On call
//   - ctx context.Context
//   - req *user.LoginUserRequest
func (_e *MockUserService_Expecter) LoginUser(ctx interface{}, req interface{}) *MockUserService_LoginUser_Call {
	return &MockUserService_LoginUser_Call{Call: _e.mock.On("LoginUser", ctx, req)}
}

func (_c *MockUserService_LoginUser_Call) Run(run func(ctx context.Context, req *user.LoginUserRequest)) *MockUserService_LoginUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.LoginUserRequest
		if args[1] != nil {
			arg1 = args[1].(*user.LoginUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_LoginUser_Call) Return(user1 *user.User, err error) *MockUserService_LoginUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserService_LoginUser_Call) RunAndReturn(run func(ctx context.Context, req *user.LoginUserRequest) (*user.User, error)) *MockUserService_LoginUser_Call {
	_c.Call.Return(run)
	return _c
}
